---
pool:
  name: DEFRA-COMMON-ubuntu2004-SSV5

variables:
  - group: entra
 
parameters:
  - name: environmentName
    displayName: Environment
    type: string
    default: entra
    values:
      - entra

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

    - repository: PltConfig
      name: DEFRA/plt-config
      endpoint: DEFRA
      type: github
      ref: refs/heads/ml/initial-structure


stages:

  - stage: create_aad_groups
    displayName: Create AAD Groups
    jobs:
      - deployment: CreateAADGroups
        displayName: Create AAD Groups
        environment:
          name: "${{ parameters.environmentName }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: PltConfig
                - task: AzurePowerShell@5
                  displayName: Run Create-AADGroups script
                  inputs:
                    azureSubscription: 'AZR-ADP-SSV5-DEFRA-AIE'
                    ScriptType: 'FilePath'
                    ScriptPath: '$(Pipeline.Workspace)/s/scripts/pipeline/Create-AADGroups.ps1'
                    ScriptArguments: >
                      -AADGroupsJsonManifestPath '$(Pipeline.Workspace)/PltConfig/vars/entra/aad-group.json'
                      -ClientId $(entraSPClientId)
                      -TenantId $(tenantId)
                      -ClientSecret $(entraSPToken)
                    azurePowerShellVersion: 'LatestVersion'
                    pwsh: true
                    addSpnToEnvironment: false
                    workingDirectory: '$(Pipeline.Workspace)/s' 
